### ISSUE TITLE
5 days forecast not working?

### ISSUE THREAD

**Issue by marcschut002** [abaretta/nu.baretta.openweathermap#2]
I have successfully added the current weather information with my API key, but I can't get the 5 day forecast working. When should the information from OpenWeatherMap be available? I have waited for 6h but still no data.

![screenshot 2018-05-15_14-35-36](https://user-images.githubusercontent.com/38959867/40056980-453099e8-584d-11e8-972a-558bc4fb8f23.png)

![screenshot 2018-05-15_14-32-54](https://user-images.githubusercontent.com/38959867/40056988-4dcaa364-584d-11e8-837f-823503be9af9.png)

**Comment by marcschut002** [comment]
After a full day the data finally came in and I could see the forecast, but suddenly the forecast stops without reason. This insight shows a blue line for the current temp. from openweathermap and the pink  line shows the forecast (see settings in first post) . Looks like it is not as stable as I wish. Is this something that could be debugged and fixed?
![screenshot 2018-05-21_11-22-06](https://user-images.githubusercontent.com/38959867/40300677-3ed81f3e-5cea-11e8-87ec-9e100beac22a.png)

**Comment by abaretta** [comment]
Others have found that this happens even though the polling action is successful, the data returned is simply unchanged. By default Homey Insights are only updated when the plotted values have actually changed. 

All in all this appears to be caused by missing data (updates) in the OWM data itself. 

According to OWM, availability is limited to 95% for their free service (see https://openweathermap.org/price).
