### ISSUE TITLE
can't add 2 virtual devices

### ISSUE THREAD

**Issue by hplos** [abaretta/nu.baretta.openweathermap#9]
I can't get weather info from a second 'device'. ths first one should check the current weather, but in the morning, when my screens are going up, I want to know the max temp of the day. If that's hi, that I can leave my screens down.

The current weather doesn't have (a working) max temp, en the 16 day forcase doesn't receive any date.

plz help :)

**Comment by abaretta** [comment]
Not receiving data is most often caused by the app not being able to resolve the location. Are you using Homey's location (ie. by not filling in anything for the location so Homey's GPS coordinates are used)?

**Comment by abaretta** [comment]
I forgot to mention that the current weather table does not have a min/max temperature, at least the data returned by the API is not what you would expect (which is why it is not used in the app), see OWM's explanation at https://openweathermap.org/current: 

"Please, do not confuse min/max parameters in our weather APIs.

In Current weather API, Hourly forecast API and 5 day / 3 hour forecast API - temp_min and temp_max are optional parameters mean min / max temperature in the city at the current moment to see deviation from current temp just for your reference. For large cities and megalopolises geographically expanded it might be applicable. In most cases both temp_min and temp_max parameters have the same volume as 'temp'. Please, use temp_min and temp_max parameters in current weather API optionally.
In 16 Day forecast - min and max mean maximum and minimum temperature in the day."

**Comment by hplos** [comment]
> Not receiving data is most often caused by the app not being able to resolve the location. Are you using Homey's location (ie. by not filling in anything for the location so Homey's GPS coordinates are used)?

No I entered my location, the same way I dit for the current weather

In a flow the max temperature seams to be working (or is the same as the current temp)

It is a working for me now. I'm using the max temp (or current temp) to decide if my roller shutters should go up or not :). If the current temp is above 22 my shutters close again, first it seamed strange that the date wasn't gomming, but the api does something you wouldn't expect...
